# introduce a new language server
[language-server.scls]
command = "simple-completion-language-server"

[language-server.scls.config]
max_completion_items = 20            # set max completion results len for each group: words, snippets, unicode-input
snippets_first = true                # completions will return before snippets by default
snippets_inline_by_word_tail = false # suggest snippets by WORD tail, for example text `xsq|` become `x^2|` when snippet `sq` has body `^2`
feature_words = true                 # enable completion by word
feature_snippets = true              # enable snippets
feature_unicode_input = true         # enable "unicode input"
feature_paths = true                 # enable path completion
feature_citations = false            # enable citation completion (only on `citation` feature enabled)

# write logs to /tmp/completion.log
[language-server.scls.environment]
RUST_LOG = "info,simple-completion-language-server=info"
LOG_FILE = "/tmp/completion.log"

[language-server.steel-language-server]
command = "/home/yanni/.cargo/bin/steel-language-server"
args = []

[language-server.ruff]
command = "ruff-lsp"

[language-server.rust-analyzer.config]
check.command = "clippy"

# append language server to existing languages
[[language]]
name = "python"
language-servers = [ "scls", "pylsp", "ruff" ]
formatter = { command = "ruff", args = ["format", "-" ] }
auto-format = true


[[language]]
name = "git-commit"
language-servers = [ "scls" ]

[[language]]
name = "toml"
language-servers = [ "scls", "taplo" ]

[[language]]
name = "rust"
language-servers = [ "scls", "rust-analyzer" ]
formatter = { command = "rustfmt" }
auto-format = true

[[language]]
name = "latex"
language-servers = [ "scls", "texlab" ]

[[language]]
name = "nix"
language-servers = [ "scls", "nil" ]
formatter = { command = "nixfmt" }
auto-format = false

[[language]]
name = "yaml"
language-servers = [ "scls", "yaml-language-server" ]

[[language]]
name = "kdl"
language-servers = [ "scls" ]
auto-format = false

[[language]]
name = "scheme"
formatter = { command = "raco", args = ["fmt", "-i"] }
auto-format = false
language-servers = [ "scls", "steel-language-server" ]

[[language]]
name = "markdown"
language-servers = [ "scls", "marksman", "markdown-oxide" ]
auto-format = false
file-types = [ "md", "qmd" ]
# comment-token = "#"

[[language]]
name = "r"
language-servers = [ "scls", "r" ]
formatter = { command = "rstyler" }
auto-format = true

# introduce a new language to enable completion on any doc by forcing set language with :set-language stub
[[language]]
name = "stub"
scope = "text.stub"
file-types = []
shebangs = []
roots = []
auto-format = false
language-servers = [ "scls" ]
