require("plugins.mini")
require("plugins.treesitter")
require("plugins.telescope")
require("plugins.which-key")
require("plugins.comment")
require("plugins.lsp")
require("plugins.colorizer")
require("plugins.fidget")
require("plugins.gitsigns")
-- require("plugins.obsidian")
require("plugins.todo-comments")
require("plugins.toggleterm")
require("plugins.undotree")
-- require("plugins.searchbox")
require("plugins.icon-picker")
require("plugins.glow")
-- require("plugins.neoclip")
require("plugins.spectre")
require("plugins.neogit")
-- require("plugins.yarepl")
require("plugins.quarto")
-- require("plugins.slime")
require("plugins.oil")
-- require("plugins.markdown")
require("plugins.gitpad")
-- require("plugins.r-nvim")
-- require("plugins.alpha")
--require("plugins.autopairs")
--require("plugins.illuminate")
--require("plugins.indent-blankline")
-- require("plugins.leap")
-- require("plugins.lualine")
-- require("plugins.neorg")
