# Don't print a new line at the start of the prompt
add_newline = false

# Make prompt a single line instead of two lines
[line_break]
disabled = true

# Replace the "❯" symbol in the prompt with "➜"
[character]
# The "success_symbol" segment is being set to "➜" with the color "bold green"
# use_symbol_for_status = true
success_symbol = "[➜](bold red)"
error_symbol = "[✖](bold red)"

[cmd_duration]
disabled = true

[aws]
symbol = ""

[conda]
symbol = " "
format = "[$symbol$environment]($style) "

[dart]
symbol = " "

[directory]
read_only = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "

# [haskell]
# symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "
format = "[$symbol]($style)"

[memory_usage]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "
format = "[$symbol]($style)"
disabled = true

[package]
symbol = " "

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "
format = '[${symbol}${pyenv_prefix}(\($virtualenv\))]($style)'


[ruby]
symbol = " "

[rust]
symbol = " "

[swift]
symbol = "ﯣ "

[hostname]
disabled=true
